apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deploy
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "catalog"
        volumeMounts:
        - name: html-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-config
        configMap:
          name: catalog-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-html
  namespace: microservices
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Catalog Service</title></head>
    <body>
      <h1>Catalog Microservice</h1>
      <p>Service: catalog</p>
      <p>Hostname: <script>document.write(location.hostname)</script></p>
      <p>Timestamp: <script>document.write(new Date().toISOString())</script></p>
      <div id="products">
        <h2>Products:</h2>
        <ul>
          <li>Product 1 - $10</li>
          <li>Product 2 - $20</li>
          <li>Product 3 - $30</li>
        </ul>
      </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: microservices
spec:
  selector:
    app: catalog
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
